[book]
authors = ["google-labs-jules[bot]"]
language = "en"
multilingual = false
src = "src"
title = "The Architecture of Digital Enclosure"

[build]
build-dir = "book"

[output.html]

[output.llms-full-txt]
command = "python3 ../../bin/gen-llms-txt.py"
